---
- name: Create Oracle user
  hosts: localhost
  connection: local
  become: yes  # To elevate privileges as needed

  tasks:

    # **************************************************

    - name: Create oinstall group
      group:
        name: oinstall
        gid: 54321

    - name: Create oracle user
      user:
        name: oracle
        shell: /bin/bash
        uid: 54321
        group: oinstall

#    - name: Set password for oracle user
#      shell: echo "oracle_password" | passwd --stdin oracle

# **************************************************
    - name: Create installation directory
      file:
        path: /u01/app/oracle/product/12.2.1
        state: directory

    - name: create domain folder
      file:
        path: /u01/app/oracle/config/domains
        state: directory

    - name: application folder
      file:
        path: /u01/app/oracle/config/applications
        state: directory

    - name: Change ownership to oracle:oinstall
      command: chown -R oracle:oinstall /u01

    - name: Change permissions to 775
      command: chmod -R 775 /u01/

    - name: Copy JDK binary to /u01/app/oracle/
      ansible.builtin.copy:
        src: jdk-8u361-linux-x64.tar.gz
        dest: /u01/app/oracle/
        owner: oracle
        group: oinstall

    - name: Extract binary
      ansible.builtin.unarchive:
        src: /u01/app/oracle/jdk-8u361-linux-x64.tar.gz
        dest: /u01/app/oracle/
        owner: oracle
        group: oinstall
        remote_src: yes

    - name: Change ownership to oracle:oinstall
      command: chown -R oracle:oinstall /u01/app/oracle/

    - name: Change permissions to 775
      command: chmod -R 775 /u01/app/oracle/
      
  # fmw_12.2.1.3.0_wls_Disk1_1of1.zip
  
    - name: Copy Install file to /u01/app/oracle/
      ansible.builtin.copy:
        src: fmw_12.2.1.3.0_wls_Disk1_1of1.zip
        dest: /u01/app/oracle/
        owner: oracle
        group: oinstall

    - name: Extract binary
      ansible.builtin.unarchive:
        src: /u01/app/oracle/fmw_12.2.1.3.0_wls_Disk1_1of1.zip
        dest: /u01/app/oracle/
        owner: oracle
        group: oinstall
        remote_src: yes
  
